# Generated by Django 5.2.7 on 2025-12-07 17:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_name', models.CharField(max_length=200)),
                ('project_location', models.TextField()),
                ('site_supervisor', models.CharField(max_length=100)),
                ('purpose', models.TextField(help_text='Purpose of the material request')),
                ('delivery_date_needed', models.DateField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ordered', 'Ordered')], default='pending', max_length=10)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('specification', models.CharField(blank=True, help_text='Size, grade, brand, etc.', max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('bags', 'Bags'), ('cubic_meters', 'Cubic Meters'), ('square_meters', 'Square Meters'), ('linear_meters', 'Linear Meters'), ('tons', 'Tons'), ('liters', 'Liters'), ('sets', 'Sets'), ('boxes', 'Boxes'), ('rolls', 'Rolls')], max_length=20)),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier_preference', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.materialrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
