# Generated by Django 5.2.7 on 2025-12-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='purchase_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved_for_purchase', 'Approved for Purchase'), ('rejected', 'Rejected')], default='pending', max_length=25),
        ),
    ]
